### ISSUE TITLE
ENOENT: no such file or directory, open '/var/bin/chromium.br'

### ISSUE THREAD

**Issue by aleksanderhayes** [saasify-sh/puppeteer-serverless#5]
> Jan 18, 12:40:32 UTC
START RequestId: 9d7b87b5-d99a-44ba-9905-3da1d991992d Version: $LATEST
Jan 18, 12:40:32 UTC
2021-01-18T12:40:32.376Z 9d7b87b5-d99a-44ba-9905-3da1d991992d ERROR Invoke Error
{
    "errorType": "Error",
    "errorMessage": "ENOENT: no such file or directory, open '/var/bin/chromium.br'",
    "code": "ENOENT",
    "errno": -2,
    "syscall": "open",
    "path": "/var/bin/chromium.br",
    "stack": [
        "Error: ENOENT: no such file or directory, open '/var/bin/chromium.br'"
    ]
}
Jan 18, 12:40:32 UTC
END RequestId: 9d7b87b5-d99a-44ba-9905-3da1d991992d
Jan 18, 12:40:32 UTC
REPORT RequestId: 9d7b87b5-d99a-44ba-9905-3da1d991992d Duration: 10.58 ms Billed Duration: 11 ms Memory Size: 1024 MB Max Memory Used: 77 MB Init Duration: 218.67 ms

`serverless install --url https://github.com/AnomalyInnovations/serverless-nodejs-starter --name notes-api`

use above command create project, deploy to aws, then get this error.

try this, neither work.
[https://stackoverflow.com/questions/59987104/chrome-binary-not-found-on-aws-lambda-using-serverless-and-chrome-aws-lambda-nod](url)

**Comment by transitive-bullshit** [comment]
You should just use `chromium-aws-lambda`.

It now solves everything including local development that this package was originally intended for.
